return {
  ft = {'agda', 'agda.markdown'},
  requires = {
    {'neovimhaskell/nvim-hs.vim'},
    {'liuchengxu/vim-which-key'}
  },
  config =
    function ()
      vim.g.cornelis_split_direction = 'Vertical'
      vim.cmd[[
        call cornelis#bind_input("forall", "∀")
        call cornelis#bind_input("exists", "∃")
        call cornelis#bind_input("Pi", "Π")
        call cornelis#bind_input("Sigma", "Σ")
        call cornelis#bind_input("leq", "≤")
        call cornelis#bind_input("geq", "≥")
        call cornelis#bind_input("equiv", "≡")
        call cornelis#bind_input("lambda", "λ")
        call cornelis#bind_input("cdot", "∙")
        call cornelis#bind_input("star", "★")
        call cornelis#bind_input("circ", "∘")
        call cornelis#bind_input("times", "×")

        call cornelis#bind_input("sim", "∼")
        call cornelis#bind_input("simeq", "≃")
        call cornelis#bind_input("cong", "≅")

        call cornelis#bind_input("alpha", "α")
        call cornelis#bind_input("beta", "β")
        call cornelis#bind_input("gamma", "γ")
        call cornelis#bind_input("eps", "δ")
        call cornelis#bind_input("zeta", "ζ")
        call cornelis#bind_input("eta", "η")
        call cornelis#bind_input("theta", "θ")
        call cornelis#bind_input("iota", "ι")
        call cornelis#bind_input("kappa", "κ")
        call cornelis#bind_input("mu", "μ")
        call cornelis#bind_input("nu", "ν")
        call cornelis#bind_input("xi", "ξ")
        call cornelis#bind_input("omicron", "ο")
        call cornelis#bind_input("pi", "π")
        call cornelis#bind_input("rho", "ρ")
        call cornelis#bind_input("sigma", "σ")
        call cornelis#bind_input("tau", "τ")
        call cornelis#bind_input("upsilon", "υ")
        call cornelis#bind_input("phi", "φ")
        call cornelis#bind_input("chi", "χ")
        call cornelis#bind_input("psi", "ψ")
        call cornelis#bind_input("omega", "ω")

        call cornelis#bind_input("AA", "𝔸")
        call cornelis#bind_input("BB", "𝔹")
        call cornelis#bind_input("CC", "ℂ")
        call cornelis#bind_input("DD", "𝔻")
        call cornelis#bind_input("EE", "𝔼")
        call cornelis#bind_input("FF", "𝔽")
        call cornelis#bind_input("GG", "𝔾")
        call cornelis#bind_input("HH", "ℍ")
        call cornelis#bind_input("II", "𝕀")
        call cornelis#bind_input("JJ", "𝕁")
        call cornelis#bind_input("KK", "𝕂")
        call cornelis#bind_input("LL", "𝕃")
        call cornelis#bind_input("MM", "𝕄")
        call cornelis#bind_input("NN", "ℕ")
        call cornelis#bind_input("OO", "𝕆")
        call cornelis#bind_input("PP", "ℙ")
        call cornelis#bind_input("QQ", "ℚ")
        call cornelis#bind_input("RR", "ℝ")
        call cornelis#bind_input("SS", "𝕊")
        call cornelis#bind_input("TT", "𝕋")
        call cornelis#bind_input("UU", "𝕌")
        call cornelis#bind_input("VV", "𝕍")
        call cornelis#bind_input("WW", "𝕎")
        call cornelis#bind_input("XX", "𝕏")
        call cornelis#bind_input("YY", "𝕐")
        call cornelis#bind_input("ZZ", "ℤ")
        call cornelis#bind_input("bb00", "𝟘")
        call cornelis#bind_input("bb11", "𝟙")
        call cornelis#bind_input("bb22", "𝟚")
        call cornelis#bind_input("bb33", "𝟛")
        call cornelis#bind_input("bb44", "𝟜")
        call cornelis#bind_input("bb55", "𝟝")
        call cornelis#bind_input("bb66", "𝟞")
        call cornelis#bind_input("bb77", "𝟟")
        call cornelis#bind_input("bb88", "𝟠")
        call cornelis#bind_input("bb99", "𝟡")
      ]]
    end
}
